name: lighthouse_provider
description: Lighthouse provider, provides VR lighthouses the "easy" way.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  meta: ">=1.16.0 <2.0.0"
  mutex: ">=3.1.0 <4.0.0"
  rxdart: ">=0.28.0 <1.0.0"
  tuple: ">=2.0.2 <3.0.0"
  collection: ">=1.19.1 <2.0.0"
  convert: ">=3.1.2 <4.0.0"
  lighthouse_back_end:
    path: ../lighthouse_back_end
  shared_platform:
    path: ../../shared/shared_platform
  lighthouse_logger:
    path: ../lighthouse_logger

dev_dependencies:
  lints: ^6.0.0
  test: ">=1.25.12 < 2.0.0"
  fake_back_end:
    path: ../lighthouse_back_ends/fake_back_end
  lighthouse_providers:
    path: ../lighthouse_providers
  lighthouse_test_helper:
    path: ../lighthouse_test_helper
