name: flutter_web_bluetooth_back_end
description: A lighthouse back end to use flutter web bluetooth.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter_web_bluetooth: ^1.0.0
  mutex: ">=3.1.0 <4.0.0"
  rxdart: ">=0.28.0 <1.0.0"
  lighthouse_back_end:
    path: ../../lighthouse_back_end
  lighthouse_provider:
    path: ../../lighthouse_provider
  lighthouse_logger:
    path: ../../lighthouse_logger

dev_dependencies:
  lints: ^6.0.0
  test: ">=1.25.12 < 2.0.0"
