name: Flutter_Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Restore packages
        run: |
          flutter pub get
          cd lighthouse_provider/lighthouse_back_end
          dart pub get
          cd ../lighthouse_back_ends/bluez_back_end
          dart pub get
          cd ../fake_back_end
          dart pub get
          cd ../flutter_blue_plus_back_end
          flutter pub get
          cd ../quick_blue_back_end
          flutter pub get
          cd ../flutter_web_bluetooth_back_end
          dart pub get
          cd ../../lighthouse_logger
          dart pub get
          cd ../lighthouse_provider
          dart pub get
          cd ../lighthouse_providers
          dart pub get
          cd ../lighthouse_test_helper
          dart pub get
          cd ../../shared/shared_platform
          dart pub get
          cd ../../

      - name: Generate code
        run: flutter packages pub run build_runner build

      - name: Analyze
        run: dart analyze

      - name: Formatted
        run: dart format --set-exit-if-changed .

      - name: Run tests
        run: flutter test --coverage

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
